package dev.eliaschen.mito.route

import dev.eliaschen.mito.db.ErrorResponse
import dev.eliaschen.mito.db.Pagination
import dev.eliaschen.mito.db.PosePayload
import dev.eliaschen.mito.db.Workout
import dev.eliaschen.mito.db.WorkoutDao
import dev.eliaschen.mito.db.WorkoutPayload
import io.github.smiley4.ktoropenapi.delete
import io.github.smiley4.ktoropenapi.get
import io.github.smiley4.ktoropenapi.post
import io.github.smiley4.ktoropenapi.put
import io.ktor.http.HttpStatusCode
import io.ktor.server.request.receive
import io.ktor.server.response.respond
import io.ktor.server.routing.Route
import io.ktor.server.routing.route

fun Route.workout() {
    route("workout") {
        get({
            tags = listOf("Workout")
            summary = "List workouts"
            description = "Returns all stored workouts with their poses in order."
            request {
                queryParameter<String>("search") {}
                queryParameter<Int>("limit") {
                    description = "Max items per page, defaults to 10"
                }
                queryParameter<Int>("page") {
                    description = "1-based page number, defaults to 1, 0 to show pagination info"
                }
            }
            response {
                HttpStatusCode.OK to { body<List<Workout>>() }
            }
        }) {
            val search = call.request.queryParameters["search"] ?: ""
            val limit = (call.request.queryParameters["limit"]?.toIntOrNull() ?: 10).coerceIn(1, 100)
            val page = (call.request.queryParameters["page"]?.toIntOrNull() ?: 1).coerceAtLeast(1)
            val list = WorkoutDao.getAll(search, limit, page)
            call.respond(list)
        }

        post({
            tags = listOf("Workout")
            summary = "Create a workout"
            description =
                "Stores a new workout. `poses` is the ordered list of poses to play through. " +
                        "`id`, `createdAt`, `updatedAt` and per-pose ids are generated by the server."
            request {
                body<WorkoutPayload> {
                    example("default") {
                        value = WorkoutPayload(
                            name = "併步",
                            description = "Wake-up stretch sequence",
                            poses = listOf(
                                PosePayload(location = 5, delayMillis = 1500),
                                PosePayload(location = 1, delayMillis = 1000),
                                PosePayload(location = 3, delayMillis = 1500)
                            ),
                        )
                    }
                }
            }
            response {
                HttpStatusCode.OK to { body<Workout>() }
                HttpStatusCode.InternalServerError to { body<ErrorResponse>() }
            }
        }) {
            val req = call.receive<WorkoutPayload>()
            call.respond(WorkoutDao.insert(req))
        }
        route("{id}") {
            get({
                tags = listOf("Workout")
                summary = "Get a workout"
                request {
                    pathParameter<String>("id") {
                        description = "id of the workout"
                    }
                }
                response {
                    HttpStatusCode.OK to { body<Workout>() }
                    HttpStatusCode.NotFound to { body<ErrorResponse>() }
                }
            }) {
                val id = call.parameters["id"]!!
                val workout = WorkoutDao.getById(id)
                    ?: return@get call.respond(HttpStatusCode.NotFound, ErrorResponse("Workout not found"))
                call.respond(workout)
            }
            put({
                tags = listOf("Workout")
                summary = "Update a workout"
                description =
                    "Replaces name, description and the ordered `poses` list. `updatedAt` is refreshed by the server."
                request {
                    pathParameter<String>("id") {
                        description = "id of the workout"
                    }
                    body<WorkoutPayload> {
                        example("default") {
                            value = WorkoutPayload(
                                name = "Morning routine",
                                description = "Wake-up stretch sequence",
                                poses = listOf(PosePayload(location = 1, delayMillis = 1500)),
                            )
                        }
                    }
                }
                response {
                    HttpStatusCode.OK to { body<Workout>() }
                    HttpStatusCode.NotFound to { body<ErrorResponse>() }
                }
            }) {
                val id = call.parameters["id"]!!
                val req = call.receive<WorkoutPayload>()
                val workout = WorkoutDao.update(id, req)
                    ?: return@put call.respond(HttpStatusCode.NotFound, ErrorResponse("Workout not found"))
                call.respond(workout)
            }
            delete({
                tags = listOf("Workout")
                summary = "Delete a workout"
                request {
                    pathParameter<String>("id") {
                        description = "id of the workout"
                    }
                }
                response {
                    HttpStatusCode.NoContent to { description = "Deleted" }
                    HttpStatusCode.NotFound to { body<ErrorResponse>() }
                }
            }) {
                val id = call.parameters["id"]!!
                if (!WorkoutDao.delete(id)) {
                    return@delete call.respond(HttpStatusCode.NotFound, ErrorResponse("Workout not found"))
                }
                call.respond(HttpStatusCode.NoContent)
            }
        }
    }
}
